repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: |
          (?x)(
            tests?/.*         # Exclude all test files/folders
            |.*test_password.* # Exclude lines with 'test_password'
            |.*TemporaryPassword123!.* # Exclude your known test password
          ) 