name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pytest
    - name: Lint with ruff
      run: ruff check .
    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest 
    - name: Integration Test (Real Servers)
      if: ${{ secrets.TEST_LINUX_HOST && secrets.TEST_WINDOWS_HOST }}
      env:
        TEST_LINUX_HOST: ${{ secrets.TEST_LINUX_HOST }}
        TEST_LINUX_USER: ${{ secrets.TEST_LINUX_USER }}
        TEST_LINUX_PASS: ${{ secrets.TEST_LINUX_PASS }}
        TEST_LINUX_PORT: ${{ secrets.TEST_LINUX_PORT }}
        TEST_WINDOWS_HOST: ${{ secrets.TEST_WINDOWS_HOST }}
        TEST_WINDOWS_USER: ${{ secrets.TEST_WINDOWS_USER }}
        TEST_WINDOWS_PASS: ${{ secrets.TEST_WINDOWS_PASS }}
        TEST_WINDOWS_PORT: ${{ secrets.TEST_WINDOWS_PORT }}
      run: pytest tests/test_integration_real_servers.py 