name: Cleanup Infrastructure

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      force_cleanup:
        description: "Force cleanup even if no workflow resources found"
        required: false
        default: false
        type: boolean
  # Run cleanup automatically after any workflow that might create infrastructure
  workflow_run:
    workflows: ["Modular CI Pipeline", "Provision Infrastructure", "Test Virtual Network Services", "Test Application Code"]
    types: [completed]
    branches: [main]

jobs:
  cleanup:
    name: Cleanup Infrastructure
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get current workflow run ID
        id: workflow_run
        run: |
          # Get the run ID from the triggering workflow
          if [ "${{ github.event.workflow_run.id }}" != "" ]; then
            echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
            echo "workflow_name=${{ github.event.workflow_run.name }}" >> $GITHUB_OUTPUT
            echo "Triggering workflow run ID: ${{ github.event.workflow_run.id }}"
          else
            echo "run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT
            echo "workflow_name=${{ github.workflow }}" >> $GITHUB_OUTPUT
            echo "Current workflow run ID: ${{ github.run_id }}"
          fi

      - name: Targeted cleanup - Remove workflow-specific key pairs
        run: |
          echo "=== TARGETED CLEANUP - KEY PAIRS ==="
          echo "Removing only workflow-specific key pairs..."
          
          # Only delete our specific key pair (Windows uses password authentication)
          aws ec2 delete-key-pair --key-name hai-ci-ec2-user-key 2>/dev/null || echo "Failed to delete hai-ci-ec2-user-key, continuing..."
          
          echo "Key pair cleanup completed"

      - name: Targeted cleanup - Delete workflow-specific EC2 instances
        run: |
          echo "=== TARGETED CLEANUP - EC2 INSTANCES ==="
          echo "Checking for workflow-specific EC2 instances..."
          
          # Get list of instances tagged with our workflow identifier and specific run ID
          instance_list=$(aws ec2 describe-instances \
            --filters "Name=tag:ManagedBy,Values=hai-ci-workflow" "Name=tag:WorkflowRunID,Values=${{ steps.workflow_run.outputs.run_id }}" \
            --query 'Reservations[].Instances[].InstanceId' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$instance_list" ]; then
            echo "Found workflow-specific instances to terminate: $instance_list"
            for instance_id in $instance_list; do
              echo "Terminating workflow instance $instance_id"
              aws ec2 terminate-instances --instance-ids $instance_id 2>/dev/null || echo "Failed to terminate instance $instance_id, continuing..."
            done
            
            # Wait for instances to be terminated
            echo "Waiting for instances to terminate..."
            for instance_id in $instance_list; do
              echo "Waiting for instance $instance_id to terminate..."
              aws ec2 wait instance-terminated --instance-ids $instance_id 2>/dev/null || echo "Instance $instance_id termination wait failed, continuing..."
            done
          else
            echo "No workflow-specific instances found for run ID ${{ steps.workflow_run.outputs.run_id }}"
          fi
          
          echo "EC2 instance cleanup completed"

      - name: Targeted cleanup - Delete workflow-specific security groups
        run: |
          echo "=== TARGETED CLEANUP - SECURITY GROUPS ==="
          echo "Checking for workflow-specific security groups..."
          
          # Get list of security groups tagged with our workflow identifier and specific run ID
          sg_list=$(aws ec2 describe-security-groups \
            --filters "Name=tag:ManagedBy,Values=hai-ci-workflow" "Name=tag:WorkflowRunID,Values=${{ steps.workflow_run.outputs.run_id }}" \
            --query 'SecurityGroups[].GroupId' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$sg_list" ]; then
            echo "Found workflow-specific security groups to delete: $sg_list"
            for sg_id in $sg_list; do
              echo "Deleting workflow security group $sg_id"
              aws ec2 delete-security-group --group-id $sg_id 2>/dev/null || echo "Failed to delete security group $sg_id, continuing..."
            done
          else
            echo "No workflow-specific security groups found for run ID ${{ steps.workflow_run.outputs.run_id }}"
          fi
          
          echo "Security group cleanup completed"

      - name: Targeted cleanup - Delete workflow-specific subnets
        run: |
          echo "=== TARGETED CLEANUP - SUBNETS ==="
          echo "Checking for workflow-specific subnets..."
          
          # Get list of subnets tagged with our workflow identifier and specific run ID
          subnet_list=$(aws ec2 describe-subnets \
            --filters "Name=tag:ManagedBy,Values=hai-ci-workflow" "Name=tag:WorkflowRunID,Values=${{ steps.workflow_run.outputs.run_id }}" \
            --query 'Subnets[].SubnetId' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$subnet_list" ]; then
            echo "Found workflow-specific subnets to delete: $subnet_list"
            for subnet_id in $subnet_list; do
              echo "Deleting workflow subnet $subnet_id"
              aws ec2 delete-subnet --subnet-id $subnet_id 2>/dev/null || echo "Failed to delete subnet $subnet_id, continuing..."
            done
          else
            echo "No workflow-specific subnets found for run ID ${{ steps.workflow_run.outputs.run_id }}"
          fi
          
          echo "Subnet cleanup completed"

      - name: Targeted cleanup - Delete workflow-specific route tables
        run: |
          echo "=== TARGETED CLEANUP - ROUTE TABLES ==="
          echo "Checking for workflow-specific route tables..."
          
          # Get list of route tables tagged with our workflow identifier and specific run ID
          rt_list=$(aws ec2 describe-route-tables \
            --filters "Name=tag:ManagedBy,Values=hai-ci-workflow" "Name=tag:WorkflowRunID,Values=${{ steps.workflow_run.outputs.run_id }}" \
            --query 'RouteTables[].RouteTableId' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$rt_list" ]; then
            echo "Found workflow-specific route tables to delete: $rt_list"
            for rt_id in $rt_list; do
              echo "Deleting workflow route table $rt_id"
              aws ec2 delete-route-table --route-table-id $rt_id 2>/dev/null || echo "Failed to delete route table $rt_id, continuing..."
            done
          else
            echo "No workflow-specific route tables found for run ID ${{ steps.workflow_run.outputs.run_id }}"
          fi
          
          echo "Route table cleanup completed"

      - name: Targeted cleanup - Delete workflow-specific internet gateways
        run: |
          echo "=== TARGETED CLEANUP - INTERNET GATEWAYS ==="
          echo "Checking for workflow-specific internet gateways..."
          
          # Get list of internet gateways tagged with our workflow identifier and specific run ID
          igw_list=$(aws ec2 describe-internet-gateways \
            --filters "Name=tag:ManagedBy,Values=hai-ci-workflow" "Name=tag:WorkflowRunID,Values=${{ steps.workflow_run.outputs.run_id }}" \
            --query 'InternetGateways[].InternetGatewayId' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$igw_list" ]; then
            echo "Found workflow-specific internet gateways to delete: $igw_list"
            for igw_id in $igw_list; do
              echo "Processing workflow IGW $igw_id"
              
              # Get VPC ID for this IGW
              vpc_id=$(aws ec2 describe-internet-gateways \
                --internet-gateway-ids $igw_id \
                --query 'InternetGateways[0].Attachments[0].VpcId' \
                --output text 2>/dev/null || echo "")
              
              if [ -n "$vpc_id" ]; then
                echo "Detaching IGW $igw_id from VPC $vpc_id"
                aws ec2 detach-internet-gateway --internet-gateway-id $igw_id --vpc-id $vpc_id 2>/dev/null || echo "Failed to detach IGW $igw_id, continuing..."
              fi
              
              echo "Deleting workflow IGW $igw_id"
              aws ec2 delete-internet-gateway --internet-gateway-id $igw_id 2>/dev/null || echo "Failed to delete IGW $igw_id, continuing..."
            done
          else
            echo "No workflow-specific internet gateways found for run ID ${{ steps.workflow_run.outputs.run_id }}"
          fi
          
          echo "Internet gateway cleanup completed"

      - name: Targeted cleanup - Delete workflow-specific VPCs
        run: |
          echo "=== TARGETED CLEANUP - VPCS ==="
          echo "Cleaning up only workflow-specific VPCs..."
          
          # Get list of VPCs tagged with our workflow identifier and specific run ID
          vpc_list=$(aws ec2 describe-vpcs \
            --filters "Name=tag:ManagedBy,Values=hai-ci-workflow" "Name=tag:WorkflowRunID,Values=${{ steps.workflow_run.outputs.run_id }}" \
            --query 'Vpcs[].VpcId' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$vpc_list" ]; then
            echo "Found workflow-specific VPCs to delete: $vpc_list"
            for vpc_id in $vpc_list; do
              echo "Deleting workflow VPC $vpc_id"
              aws ec2 delete-vpc --vpc-id $vpc_id 2>/dev/null || echo "Failed to delete VPC $vpc_id, continuing..."
            done
          else
            echo "No workflow-specific VPCs found for run ID ${{ steps.workflow_run.outputs.run_id }}"
          fi
          
          echo "VPC cleanup completed"

      - name: Cleanup summary
        run: |
          echo "=== TARGETED CLEANUP SUMMARY ==="
          echo "All targeted cleanup operations completed!"
          echo "Only resources tagged with 'ManagedBy=hai-ci-workflow' and 'WorkflowRunID=${{ steps.workflow_run.outputs.run_id }}' were cleaned up."
          echo "Existing resources not created by this specific workflow run were preserved."
          echo ""
          echo "Resources cleaned up from workflow run ${{ steps.workflow_run.outputs.run_id }}:"
          echo "- EC2 instances with ManagedBy=hai-ci-workflow and WorkflowRunID=${{ steps.workflow_run.outputs.run_id }} tags"
          echo "- Security groups with ManagedBy=hai-ci-workflow and WorkflowRunID=${{ steps.workflow_run.outputs.run_id }} tags"
          echo "- Subnets with ManagedBy=hai-ci-workflow and WorkflowRunID=${{ steps.workflow_run.outputs.run_id }} tags"
          echo "- Route tables with ManagedBy=hai-ci-workflow and WorkflowRunID=${{ steps.workflow_run.outputs.run_id }} tags"
          echo "- Internet gateways with ManagedBy=hai-ci-workflow and WorkflowRunID=${{ steps.workflow_run.outputs.run_id }} tags"
          echo "- VPCs with ManagedBy=hai-ci-workflow and WorkflowRunID=${{ steps.workflow_run.outputs.run_id }} tags"
          echo "- Key pairs: hai-ci-ec2-user-key" 