name: Modular CI Pipeline

on:
  push:
    branches: [main]

jobs:
  provision-infra:
    uses: ./.github/workflows/provision-infra.yml

  test-vns:
    needs: provision-infra
    uses: ./.github/workflows/test-vns.yml
    with:
      linux_ip: ${{ needs.provision-infra.outputs.linux_ip }}
      windows_ip: ${{ needs.provision-infra.outputs.windows_ip }}
      detected_username: ${{ needs.provision-infra.outputs.detected_username }}

  test-code:
    needs: provision-infra
    uses: ./.github/workflows/test-code.yml
    with:
      linux_ip: ${{ needs.provision-infra.outputs.linux_ip }}
      windows_ip: ${{ needs.provision-infra.outputs.windows_ip }}
      detected_username: ${{ needs.provision-infra.outputs.detected_username }}

  cleanup:
    needs: [provision-infra, test-vns, test-code]
    uses: ./.github/workflows/cleanup.yml
