name: Test AWS Credentials

on:
  workflow_dispatch:

jobs:
  test-credentials:
    name: Test AWS Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets availability
        run: |
          echo "=== SECRETS AVAILABILITY CHECK ==="
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "✅ AWS_ACCESS_KEY_ID is set (length: ${#AWS_ACCESS_KEY_ID})"
          else
            echo "❌ AWS_ACCESS_KEY_ID is NOT set"
          fi
          
          if [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "✅ AWS_SECRET_ACCESS_KEY is set (length: ${#AWS_SECRET_ACCESS_KEY})"
          else
            echo "❌ AWS_SECRET_ACCESS_KEY is NOT set"
          fi
          
          echo "=== END SECRETS CHECK ==="

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test AWS credentials
        run: |
          echo "=== AWS CREDENTIALS TEST ==="
          echo "Testing AWS credentials..."
          aws sts get-caller-identity
          echo "✅ AWS credentials are working!"
          
          echo "Testing EC2 access..."
          aws ec2 describe-regions --query 'Regions[0].RegionName' --output text
          echo "✅ EC2 access is working!"
          
          echo "=== END AWS TEST ===" 